# Generated from R:\build\master\gcc_dwarf
# Generated by sdk/tools/gen_baseaddress.py

set(baseaddress_ntdll                          0x7c920000) # should be above 0x7c920000
set(baseaddress_kernel32                       0x7c4f0000)
set(baseaddress_user32                         0x7bfc0000)
