# Generated from C:\ReactOS\build-msvc-x64
# Generated by sdk/tools/gen_baseaddress.py

set(baseaddress_ntdll                          0x7ffb7000000) # should be above 0x7ffb7000000
set(baseaddress_kernel32                       0x7ffb6000000)
set(baseaddress_user32                         0x7ffb5000000)
