# Generated from ../../output-VS-i386
# Generated by sdk/tools/gen_baseaddress.py

set(baseaddress_ntdll                          0x7c920000) # should be above 0x7c920000
set(baseaddress_kernel32                       0x7c640000)
set(baseaddress_user32                         0x7c500000)
